[jellyfin]
hostname = https://jellyfin.yourserver
username = user
password = pass
libraries = Music

[mpd]
enabled = true
# Useful if you want to control this instance from a remote MPD client
hostname = 0.0.0.0
port = 6600
# This will help avoid timeout errors for  artists or folders with large amounts of files
connection_timeout = 300

# Used in the event you want to control this system from a web browser
[http]
enabled = true
hostname = 0.0.0.0
port = 6680

[audio]
output = autoaudiosink

[m3u]
enabled = true
base_dir = 
playlists_dir = 

[file]
enabled = true
media_dirs = 
  ~/|Home
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000
